# non-secret application settings (consumed by php-fpm/nginx)
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-config
data:
  APP_TITLE: "AstridApp"
  DB_NAME: "appdb"
  DB_USER: "appuser"
  DB_HOST: "devdb"
